import { regionForSlate } from "./regions";
import { DEFAULT_RVO } from "./rvo";
import { buildSpecs, defaultEthanolMode, freightPerGalFor, GRADE_OPTIONS, rackPricePerBbl } from "./specs";
import type { Blendstock, Plant, ProductTank, RegionId, SlateId, StreamKey, TankId } from "./types";

type StreamBase = Omit<Blendstock, "id" | "regionId">;

function colonialStreams(): StreamBase[] {
  return [
    {
      streamKey: "nbutane",
      name: "n-Butane",
      shortName: "nC4",
      family: "LPG",
      color: "#f59e0b",
      ron: 93,
      mon: 90,
      rvp: 52,
      specificGravity: 0.584,
      sulfurPpm: 4,
      benzeneVolPct: 0,
      aromaticsVolPct: 0,
      olefinsVolPct: 0,
      oxygenWtPct: 0,
      t10F: 20,
      t50F: 31,
      t90F: 31,
      e200VolPct: 100,
      e300VolPct: 100,
      costPerBbl: 46,
      inventoryBbl: 900,
      minLiftBbl: 0,
      maxLiftBbl: 900,
      minVolPct: 0,
      maxVolPct: 8,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "isomerate",
      name: "Isomerate",
      shortName: "ISO",
      family: "Light naphtha",
      color: "#38bdf8",
      ron: 87,
      mon: 84.5,
      rvp: 13.4,
      specificGravity: 0.655,
      sulfurPpm: 1,
      benzeneVolPct: 0.1,
      aromaticsVolPct: 0.6,
      olefinsVolPct: 0.4,
      oxygenWtPct: 0,
      t10F: 110,
      t50F: 140,
      t90F: 180,
      e200VolPct: 85,
      e300VolPct: 100,
      costPerBbl: 88,
      inventoryBbl: 2200,
      minLiftBbl: 0,
      maxLiftBbl: 2200,
      minVolPct: 0,
      maxVolPct: 35,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "lsr",
      name: "Light naphtha",
      shortName: "LN",
      family: "Naphtha",
      color: "#94a3b8",
      ron: 70,
      mon: 68,
      rvp: 12.2,
      specificGravity: 0.68,
      sulfurPpm: 35,
      benzeneVolPct: 0.55,
      aromaticsVolPct: 6,
      olefinsVolPct: 1,
      oxygenWtPct: 0,
      t10F: 125,
      t50F: 175,
      t90F: 245,
      e200VolPct: 58,
      e300VolPct: 92,
      costPerBbl: 72,
      inventoryBbl: 1800,
      minLiftBbl: 0,
      maxLiftBbl: 1800,
      minVolPct: 0,
      maxVolPct: 30,
      enabled: true,
      naphtha: "light",
    },
    {
      streamKey: "heavy-naphtha",
      name: "Heavy naphtha",
      shortName: "HN",
      family: "Naphtha",
      color: "#78716c",
      ron: 64,
      mon: 62,
      rvp: 4.4,
      specificGravity: 0.762,
      sulfurPpm: 85,
      benzeneVolPct: 1.85,
      aromaticsVolPct: 15,
      olefinsVolPct: 2,
      oxygenWtPct: 0,
      t10F: 190,
      t50F: 270,
      t90F: 348,
      e200VolPct: 12,
      e300VolPct: 48,
      costPerBbl: 68,
      inventoryBbl: 1500,
      minLiftBbl: 0,
      maxLiftBbl: 1500,
      minVolPct: 0,
      maxVolPct: 25,
      enabled: true,
      naphtha: "heavy",
    },
    {
      streamKey: "reformate",
      name: "Reformate",
      shortName: "REF",
      family: "Aromatic",
      color: "#fb7185",
      ron: 98,
      mon: 88,
      rvp: 4.2,
      specificGravity: 0.812,
      sulfurPpm: 1,
      benzeneVolPct: 2.4,
      aromaticsVolPct: 66,
      olefinsVolPct: 0.8,
      oxygenWtPct: 0,
      t10F: 200,
      t50F: 260,
      t90F: 330,
      e200VolPct: 18,
      e300VolPct: 55,
      costPerBbl: 104,
      inventoryBbl: 2800,
      minLiftBbl: 0,
      maxLiftBbl: 2800,
      minVolPct: 0,
      maxVolPct: 40,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "fcc",
      name: "FCC gasoline",
      shortName: "FCC",
      family: "Cracked",
      color: "#a78bfa",
      ron: 91.5,
      mon: 81,
      rvp: 7.2,
      specificGravity: 0.746,
      sulfurPpm: 18,
      benzeneVolPct: 0.7,
      aromaticsVolPct: 27,
      olefinsVolPct: 21,
      oxygenWtPct: 0,
      t10F: 140,
      t50F: 220,
      t90F: 340,
      e200VolPct: 35,
      e300VolPct: 70,
      costPerBbl: 91,
      inventoryBbl: 4500,
      minLiftBbl: 0,
      maxLiftBbl: 4500,
      minVolPct: 0,
      maxVolPct: 50,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "alkylate",
      name: "Alkylate",
      shortName: "ALK",
      family: "Alkylate",
      color: "#34d399",
      ron: 96,
      mon: 94,
      rvp: 4.6,
      specificGravity: 0.698,
      sulfurPpm: 1,
      benzeneVolPct: 0,
      aromaticsVolPct: 0.2,
      olefinsVolPct: 0.4,
      oxygenWtPct: 0,
      t10F: 170,
      t50F: 220,
      t90F: 280,
      e200VolPct: 30,
      e300VolPct: 85,
      costPerBbl: 118,
      inventoryBbl: 2400,
      minLiftBbl: 0,
      maxLiftBbl: 2400,
      minVolPct: 0,
      maxVolPct: 50,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "isooctane",
      name: "Isooctane",
      shortName: "iC8",
      family: "Purchased octane",
      color: "#059669",
      ron: 100,
      mon: 100,
      rvp: 1.8,
      specificGravity: 0.692,
      sulfurPpm: 0,
      benzeneVolPct: 0,
      aromaticsVolPct: 0,
      olefinsVolPct: 0,
      oxygenWtPct: 0,
      t10F: 208,
      t50F: 211,
      t90F: 213,
      e200VolPct: 8,
      e300VolPct: 100,
      costPerBbl: 132,
      inventoryBbl: 400,
      minLiftBbl: 0,
      maxLiftBbl: 400,
      minVolPct: 0,
      maxVolPct: 25,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "lhc",
      name: "Light hydrocrackate",
      shortName: "LHC",
      family: "Hydrocrackate",
      color: "#2dd4bf",
      ron: 80,
      mon: 76,
      rvp: 8.1,
      specificGravity: 0.722,
      sulfurPpm: 2,
      benzeneVolPct: 0.2,
      aromaticsVolPct: 8,
      olefinsVolPct: 0.6,
      oxygenWtPct: 0,
      t10F: 150,
      t50F: 200,
      t90F: 290,
      e200VolPct: 40,
      e300VolPct: 80,
      costPerBbl: 84,
      inventoryBbl: 1600,
      minLiftBbl: 0,
      maxLiftBbl: 1600,
      minVolPct: 0,
      maxVolPct: 30,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "ethanol",
      name: "Ethanol",
      shortName: "EtOH",
      family: "Oxygenate",
      color: "#4ade80",
      ron: 109,
      mon: 90,
      rvp: 18,
      specificGravity: 0.789,
      sulfurPpm: 0,
      benzeneVolPct: 0,
      aromaticsVolPct: 0,
      olefinsVolPct: 0,
      oxygenWtPct: 34.73,
      t10F: 173,
      t50F: 173,
      t90F: 173,
      e200VolPct: 100,
      e300VolPct: 100,
      costPerBbl: 71,
      inventoryBbl: 1600,
      minLiftBbl: 0,
      maxLiftBbl: 1600,
      minVolPct: 0,
      maxVolPct: 10,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "natural",
      name: "Natural gasoline",
      shortName: "NG",
      family: "Condensate",
      color: "#fbbf24",
      ron: 73,
      mon: 71,
      rvp: 12.8,
      specificGravity: 0.668,
      sulfurPpm: 28,
      benzeneVolPct: 0.35,
      aromaticsVolPct: 5,
      olefinsVolPct: 1.5,
      oxygenWtPct: 0,
      t10F: 100,
      t50F: 160,
      t90F: 240,
      e200VolPct: 65,
      e300VolPct: 92,
      costPerBbl: 74,
      inventoryBbl: 900,
      minLiftBbl: 0,
      maxLiftBbl: 900,
      minVolPct: 0,
      maxVolPct: 20,
      enabled: true,
      naphtha: null,
    },
    {
      streamKey: "raffinate",
      name: "Raffinate",
      shortName: "RAF",
      family: "Extract bottoms",
      color: "#818cf8",
      ron: 62,
      mon: 60,
      rvp: 6.4,
      specificGravity: 0.718,
      sulfurPpm: 2,
      benzeneVolPct: 0.15,
      aromaticsVolPct: 5.5,
      olefinsVolPct: 0.8,
      oxygenWtPct: 0,
      t10F: 180,
      t50F: 240,
      t90F: 320,
      e200VolPct: 22,
      e300VolPct: 65,
      costPerBbl: 68,
      inventoryBbl: 700,
      minLiftBbl: 0,
      maxLiftBbl: 700,
      minVolPct: 0,
      maxVolPct: 15,
      enabled: true,
      naphtha: null,
    },
  ];
}

function stampPool(regionId: RegionId, patches: Partial<Record<StreamKey, Partial<Blendstock>>>): Blendstock[] {
  return colonialStreams().map((stream) => {
    const patch = patches[stream.streamKey] ?? {};
    const inventoryBbl = patch.inventoryBbl ?? stream.inventoryBbl;
    return {
      ...stream,
      ...patch,
      streamKey: stream.streamKey,
      regionId,
      id: `${regionId}-${stream.streamKey}`,
      inventoryBbl,
      maxLiftBbl: patch.maxLiftBbl ?? inventoryBbl,
    };
  });
}

export function defaultPool(regionId: RegionId): Blendstock[] {
  switch (regionId) {
    case "colonial":
      return stampPool("colonial", {});
    case "explorer":
      return stampPool("explorer", {
        nbutane: { inventoryBbl: 350, costPerBbl: 48 },
        isomerate: { inventoryBbl: 900, costPerBbl: 90 },
        lsr: { inventoryBbl: 1100, costPerBbl: 70, sulfurPpm: 28 },
        "heavy-naphtha": { inventoryBbl: 800, costPerBbl: 66, sulfurPpm: 70, benzeneVolPct: 1.6 },
        reformate: { inventoryBbl: 1200, costPerBbl: 102, benzeneVolPct: 2.1 },
        fcc: { inventoryBbl: 2200, costPerBbl: 89, sulfurPpm: 22 },
        alkylate: { inventoryBbl: 700, costPerBbl: 121 },
        isooctane: { inventoryBbl: 150, costPerBbl: 134 },
        lhc: { inventoryBbl: 1400, costPerBbl: 82 },
        ethanol: { inventoryBbl: 600, costPerBbl: 73 },
        natural: { inventoryBbl: 1400, costPerBbl: 71, sulfurPpm: 22 },
        raffinate: { inventoryBbl: 400, costPerBbl: 66 },
      });
    case "west-coast":
      return stampPool("west-coast", {
        nbutane: { inventoryBbl: 120, costPerBbl: 52, maxVolPct: 2 },
        isomerate: { inventoryBbl: 1800, costPerBbl: 96, rvp: 10.8, t50F: 145, e200VolPct: 88 },
        lsr: { inventoryBbl: 500, costPerBbl: 78, sulfurPpm: 6, benzeneVolPct: 0.2, rvp: 9.5, t90F: 230 },
        "heavy-naphtha": {
          inventoryBbl: 250,
          costPerBbl: 74,
          sulfurPpm: 10,
          benzeneVolPct: 0.7,
          aromaticsVolPct: 10,
          t90F: 320,
          enabled: false,
        },
        reformate: {
          inventoryBbl: 1600,
          costPerBbl: 112,
          benzeneVolPct: 0.55,
          aromaticsVolPct: 58,
          rvp: 3.6,
          t50F: 208,
          t90F: 312,
          e200VolPct: 30,
          e300VolPct: 78,
        },
        fcc: {
          inventoryBbl: 2200,
          costPerBbl: 102,
          sulfurPpm: 5,
          benzeneVolPct: 0.4,
          aromaticsVolPct: 22,
          olefinsVolPct: 7,
          rvp: 6.0,
          t50F: 198,
          t90F: 312,
          e200VolPct: 48,
          e300VolPct: 82,
        },
        alkylate: {
          inventoryBbl: 3600,
          costPerBbl: 128,
          rvp: 4.2,
          t50F: 205,
          t90F: 275,
          e200VolPct: 42,
          e300VolPct: 90,
        },
        isooctane: { inventoryBbl: 500, costPerBbl: 142 },
        lhc: { inventoryBbl: 1600, costPerBbl: 90, rvp: 6.4, t50F: 190, t90F: 300, e200VolPct: 52, e300VolPct: 86 },
        ethanol: { inventoryBbl: 900, costPerBbl: 76 },
        natural: { inventoryBbl: 150, costPerBbl: 80, enabled: false },
        raffinate: { inventoryBbl: 200, costPerBbl: 72, maxVolPct: 6, t90F: 310 },
      });
    case "mexico":
      return stampPool("mexico", {
        nbutane: { inventoryBbl: 400, costPerBbl: 44 },
        isomerate: { inventoryBbl: 1800, costPerBbl: 84 },
        lsr: { inventoryBbl: 1400, costPerBbl: 64, sulfurPpm: 45, benzeneVolPct: 0.7 },
        "heavy-naphtha": { inventoryBbl: 900, costPerBbl: 60, sulfurPpm: 110, benzeneVolPct: 2.2 },
        reformate: { inventoryBbl: 1000, costPerBbl: 98, benzeneVolPct: 3.0, aromaticsVolPct: 68 },
        fcc: {
          inventoryBbl: 2400,
          costPerBbl: 86,
          sulfurPpm: 28,
          benzeneVolPct: 0.85,
          aromaticsVolPct: 22,
          olefinsVolPct: 9,
        },
        alkylate: { inventoryBbl: 1800, costPerBbl: 112 },
        isooctane: { inventoryBbl: 200, costPerBbl: 124 },
        lhc: { inventoryBbl: 1100, costPerBbl: 78 },
        ethanol: { inventoryBbl: 400, costPerBbl: 78 },
        natural: { inventoryBbl: 1100, costPerBbl: 68, sulfurPpm: 40, benzeneVolPct: 0.5 },
        raffinate: { inventoryBbl: 500, costPerBbl: 62 },
      });
  }
}

export function defaultComponents(): Blendstock[] {
  return [
    ...defaultPool("colonial"),
    ...defaultPool("explorer"),
    ...defaultPool("west-coast"),
    ...defaultPool("mexico"),
  ];
}

export function applyEthanolMode(components: Blendstock[], mode: import("./types").EthanolMode): Blendstock[] {
  return components.map((component) => {
    if (component.streamKey !== "ethanol") return component;
    if (mode === "e0") {
      return { ...component, enabled: false, minVolPct: 0, maxVolPct: 0 };
    }
    if (mode === "e10") {
      return { ...component, enabled: true, minVolPct: 10, maxVolPct: 10 };
    }
    return { ...component, enabled: true, minVolPct: 0, maxVolPct: 10 };
  });
}

function makeTank(
  id: TankId,
  name: string,
  gradeId: ProductTank["gradeId"],
  slateId: SlateId,
  demandBbl: number,
  inventoryBbl: number,
  complianceOverlay: boolean,
): ProductTank {
  const seasonId = "summer90";
  const ethanolMode = defaultEthanolMode(slateId);
  return {
    id,
    name,
    enabled: true,
    gradeId,
    slateId,
    seasonId,
    ethanolMode,
    rvpWaiver: slateId === "cpl-cbob" || slateId === "explorer-cbob",
    specs: buildSpecs(slateId, gradeId, seasonId, ethanolMode, complianceOverlay),
    inventoryBbl,
    capacityBbl: id === "P2" ? 12000 : 28000,
    heelBbl: 400,
    demandBbl,
    rackPricePerBbl: rackPricePerBbl(gradeId, slateId),
    freightPerGal: freightPerGalFor(slateId),
  };
}

export function createDefaultPlant(): Plant {
  const complianceOverlay = true;
  return {
    complianceOverlay,
    rvo: { ...DEFAULT_RVO },
    components: defaultComponents(),
    tanks: [
      makeTank("P1", "P1", "regular", "cpl-cbob", 8000, 2200, complianceOverlay),
      makeTank("P2", "P2", "regular", "explorer-cbob", 1500, 800, complianceOverlay),
      makeTank("P3", "P3", "regular", "cpl-cbob", 2500, 1100, complianceOverlay),
    ],
  };
}

export function refreshTankSpecs(tank: ProductTank, complianceOverlay: boolean): ProductTank {
  return {
    ...tank,
    specs: buildSpecs(tank.slateId, tank.gradeId, tank.seasonId, tank.ethanolMode, complianceOverlay),
    rvpWaiver: tank.slateId === "cpl-cbob" || tank.slateId === "explorer-cbob" ? tank.rvpWaiver : false,
  };
}

export function gradeLabel(gradeId: ProductTank["gradeId"]): string {
  return GRADE_OPTIONS.find((item) => item.id === gradeId)?.label ?? gradeId;
}

export function tankRegion(tank: ProductTank): RegionId {
  return regionForSlate(tank.slateId);
}
